# Generated by Django 5.2.4 on 2025-07-08 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='kg', max_length=50)),
                ('description', models.TextField()),
                ('crop_type', models.CharField(blank=True, max_length=100, null=True)),
                ('usage', models.CharField(blank=True, max_length=200, null=True)),
                ('storage_info', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(max_length=200)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('estimated_delivery', models.CharField(blank=True, max_length=100, null=True)),
                ('seller', models.ForeignKey(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
